name: CI Test Suite

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-suite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run Web UI tests (Playwright)
      run: npx playwright install && npx playwright test

    - name: Run API tests (Supertest or Axios)
      run: npm run test:api

    - name: Set up Appium environment
      run: |
        sudo apt-get install -y default-jdk android-tools-adb
        npm install -g appium
        appium --version

    - name: Run Mobile UI tests (Appium + WDIO)
      run: npx wdio run wdio.conf.ts

    - name: Generate Allure Report
      if: always()
      run: |
        npx allure generate allure-results --clean -o allure-report
        npx allure open allure-report
